name: teb_package
description: That Exotic Bug Component Pack.
version: 0.0.2
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  mask_text_input_formatter: ^2.4.0
  fluttertoast: ^8.0.9    
  syncfusion_flutter_calendar: ^26.1.38
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.2
  nanoid: ^1.0.0   
  restart_app: ^1.2.1
  crypto: ^3.0.3
  encrypt: ^5.0.3  
  font_awesome_flutter: ^10.7.0
  package_info_plus: ^4.1.0  
  device_info_plus: ^9.1.0
  ipapi: ^2.0.0
  url_launcher: ^6.1.14  

  json_theme: ^8.0.0+2
  
  shared_preferences: ^2.2.2
  
  # image 
  file_picker: ^10.1.2
  dio: ^5.3.3

  cloud_firestore: ^5.0.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

